name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./gradlew --continue clean test -PsecretEmail=${{ secrets.EMAIL }} -PsecretPassword=${{ secrets.PASSWORD }} allureReport
    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: build/reports/
    - name: Download reports
      uses: actions/download-artifact@v2
      with:
        name: reports
        path: ~/download/path
